eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081

#spring-user-crud:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:8080